Repository redBorder/cookbook-consul, pull requests merged in 2024-05, with the labels that each got.

#7 Improvement/fix lint
  resources/attributes/default.rb
  resources/metadata.rb
  resources/providers/config.rb
  resources/recipes/default.rb
  resources/resources/config.rb
Labels: enhancement, kind/bug, lint, refactor, size/L

#8 Revert "Improvement/fix lint"
  resources/attributes/default.rb
  resources/metadata.rb
  resources/providers/config.rb
  resources/recipes/default.rb
  resources/resources/config.rb
Labels: size/L, kind/documentation

#9 Revert 7 improvement/fix lint
  resources/metadata.rb
Labels: kind/bug, size/XS

#12 Improvement/fix lint
  resources/attributes/default.rb
  resources/metadata.rb
  resources/providers/config.rb
  resources/recipes/default.rb
  resources/resources/config.rb
Labels: enhancement, lint, refactor, size/L, kind/documentation

#13 Release with lint fixes
  CHANGELOG.md
  resources/attributes/default.rb
  resources/metadata.rb
  resources/providers/config.rb
  resources/recipes/default.rb
  resources/resources/config.rb
Labels: size/L, kind/documentation
